<?php
    echo '
        <a href="index.php">
            <img class="logo" src="images/betalogo.png" alt="Beta Logo" width="75" height="75"/>
        </a>
        <nav>
            <ul class="menu-bar">
                <li class="button-menu-first"><a href="index.php">Home</a></li>
                <li class="button-menu"><a href="jobs.php">Job Description</a></li>
                <li class="button-menu"><a href="apply.php">Apply</a></li>
                <li class="button-menu"><a href="about.php">About</a></li>
                <li class="button-menu"><a href="manage.php">Manage</a></li>
                <li class="button-menu"><a href="enhancement.php">Enhance</a></li>
                <li class="button-menu"><a href="enhancement2.php">Enhance 2</a></li>
                <li class="button-menu"><a href="enhancement3.php">Enhance 3</a></li>
            </ul>
        <img class="fb-icon" src="images/FB-icon.png" alt="FB" width="30" height="30"/>
        <a href="mailto:102255792@student.swin.edu">
            <img class="email-icon" src="images/email.png" alt="EMAIL" width="30" height="30"/>
        </a>
        </nav>';
?>